<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accon\Accon.csproj" />
    <ProjectReference Include="..\Agilizone\Agilizone.csproj" />
    <ProjectReference Include="..\Aipedi\Aipedi.csproj" />
    <ProjectReference Include="..\Aiqfome\Aiqfome.csproj" />
    <ProjectReference Include="..\Americanas\Americanas.csproj" />
    <ProjectReference Include="..\AnotaAi\AnotaAi.csproj" />
    <ProjectReference Include="..\AtivMob\AtivMob.csproj" />
    <ProjectReference Include="..\B2Food\B2Food.csproj" />
    <ProjectReference Include="..\BigDim\Bigdim.csproj" />
    <ProjectReference Include="..\BigFish\BigFish.csproj" />
    <ProjectReference Include="..\CardapioWeb\CardapioWeb.csproj" />
    <ProjectReference Include="..\Cinddi\Cinddi.csproj" />
    <ProjectReference Include="..\CresceVendas\CresceVendas.csproj" />
    <ProjectReference Include="..\CRMBonus\CRMBonus.csproj" />
    <ProjectReference Include="..\Deeliv\Deeliv.csproj" />
    <ProjectReference Include="..\DegustaAi\DegustaAi.csproj" />
    <ProjectReference Include="..\DeliveryApp\DeliveryApp.csproj" />
    <ProjectReference Include="..\DeliveryDireto\DeliveryDireto.csproj" />
    <ProjectReference Include="..\DeliveryVip\DeliveryVip.csproj" />
    <ProjectReference Include="..\Epadoca\Epadoca.csproj" />
    <ProjectReference Include="..\EuFalo\EuFalo.csproj" />
    <ProjectReference Include="..\Fidelizi\Fidelizi.csproj" />
    <ProjectReference Include="..\FixeCRM\FixeCRM.csproj" />
    <ProjectReference Include="..\GloriaFood\GloriaFood.csproj" />
    <ProjectReference Include="..\Goomer\Goomer.csproj" />
    <ProjectReference Include="..\IDelivery\IDelivery.csproj" />
    <ProjectReference Include="..\Ifood\Ifood.csproj" />
    <ProjectReference Include="..\JotaJa\JotaJa.csproj" />
    <ProjectReference Include="..\Logaroo\Logaroo.csproj" />
    <ProjectReference Include="..\MarketPlace\MarketPlace.csproj" />
    <ProjectReference Include="..\MeuCardapioAi\MeuCardapioAi.csproj" />
    <ProjectReference Include="..\MultiPedido\MultiPedido.csproj" />
    <ProjectReference Include="..\OnPedido\OnPedido.csproj" />
    <ProjectReference Include="..\PixCommerce\PixCommerce.csproj" />
    <ProjectReference Include="..\Plug4Sales\Plug4Sales.csproj" />
    <ProjectReference Include="..\QueroDelivery\QueroDelivery.csproj" />
    <ProjectReference Include="..\Rappi\Rappi.csproj" />
    <ProjectReference Include="..\SelfBuyMe\SelfBuyMe.csproj" />
    <ProjectReference Include="..\Servit\Servit.csproj" />
    <ProjectReference Include="..\Simbora\Simbora.csproj" />
    <ProjectReference Include="..\SuperMenu\SuperMenu.csproj" />
    <ProjectReference Include="..\Tray\Tray.csproj" />
    <ProjectReference Include="..\UberEats\UberEats.csproj" />
    <ProjectReference Include="..\VMarket\VMarket.csproj" />
    <ProjectReference Include="..\Wedo\Wedo.csproj" />
    <ProjectReference Include="..\Woocommerce\Woocommerce.csproj" />
  </ItemGroup>
</Project>